apiVersion: v1
kind: Service
metadata:
  name: aj-nginx-public
  namespace: aj-nginx-public-ingress
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: aj-nginx-public

