apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoheaders-public
  annotations:
    kubernetes.io/ingress.class: "nginx-public"
spec:
  rules:
  - host: abdf5f7a86e3e11e8a3a00255995eb89-2116441857.us-west-2.elb.amazonaws.com
    http: 
      paths:
      - path: /echoheaders
        backend:
          serviceName: echoheaders
          servicePort: 80
